List<Map> products = [
  {
    "name": "Cucumber",
    "image": "assets/svgs/cucumber.jpg",
    "price": "N100.00",
    "farm":"Cellas Farm",
    "description":
        "Cucumber is a fresh, green, and tender vegetable. It is a member of the cabbage family, and is often used in salads, soups, and stews. It is also used in Chinese cuisine, and is a source of many health benefits.",
    "category": "Vegetables",
    "quantity": "25",
    "unit": "Kg",
    "id": "1",
    "isFavourite": false,
    "isInCart": false,
    "totalPrice": "N1000.00",
    "totalQuantity": "1",
    "totalUnit": "Kg",
    "totalAmount": "₹10",
  },
  {
    "name": "Palm Kernel",
    "image": "assets/svgs/palm.jpg",
    "price": "N10,000.00",
    "farm":"Duell Farms",
    "description":
        "Palm is a tree that is native to the Indian Subcontinent, and is one of the most widely cultivated trees in the world. It is also known as the Indian fig, and is a source of several health benefits.",
    "category": "Vegetables",
    "quantity": "1",
    "unit": "Kg",
    "id": "2",
    "isFavourite": false,
    "isInCart": false,
    "totalPrice": "N10,000.00",
    "totalQuantity": "25",
    "totalUnit": "Kg",
    "totalAmount": "₹10",
  },
  {
    "name": "Green Peas",
    "image": "assets/images/greenpeas.jpeg",
    "price": "N100.00",
    "farm":"Daks Farm",
    "description":
        "Green peas are a member of the legume family, and are native to the Indian Subcontinent. They are a source of several health benefits, including a reduction in the risk of heart disease and cancer.",
    "category": "Vegetables",
    "quantity": "1",
    "unit": "Kg",
    "id": "3",
    "isFavourite": false,
    "isInCart": false,
    "totalPrice": "₹10",
    "totalQuantity": "1",
    "totalUnit": "Kg",
    "totalAmount": "₹10",
  },
  {
    "name": "Tomato",
    "image": "assets/images/cherrypepper.jpeg",
    "price": "N500.00",
    "farm":"Cellas Farm",
    "description":
        "Tomato is a fruit, botanically a berry, of the nightshade family. It is consumed as an edible fruit, in many different colors, and is used in many different ways. It is a source of many health benefits.",
    "category": "Vegetables",
    "quantity": "1",
    "unit": "Kg",
    "id": "4",
    "isFavourite": false,
    "isInCart": false,
    "totalPrice": "₹10",
    "totalQuantity": "1",
    "totalUnit": "Kg",
    "totalAmount": "₹10",
  },
  {
    "name": "Green Peas",
    "image": "assets/images/greenpeas.jpeg",
    "price": "N2000.00",
    "farm":"Deko Farm",
    "description":
        "Green peas are a member of the legume family. They are a source of many health benefits, including a reduced risk of heart disease, and a reduced risk of cancer. They are also a source of many other health benefits.",
    "category": "Vegetables",
    "quantity": "1",
    "unit": "Kg",
    "id": "5",
    "isFavourite": false,
    "isInCart": false,
    "totalPrice": "₹10",
    "totalQuantity": "1",
    "totalUnit": "Kg",
    "totalAmount": "₹10",
  },
  {
    "name": "Cucumber",
    "image": "assets/svgs/cucumber.jpg",
    "price": "N10",
    "farm":"Zebra Farms",
    "description":
        "Cucumber is a fresh, green, and tender vegetable. It is a member of the cabbage family, and is often used in salads, soups, and stews. It is also used in Chinese cuisine, and is a source of many health benefits.",
    "category": "Vegetables",
    "quantity": "25",
    "unit": "Kg",
    "id": "6",
    "isFavourite": false,
    "isInCart": false,
    "totalPrice": "N1000.00",
    "totalQuantity": "1",
    "totalUnit": "Kg",
    "totalAmount": "₹10",
  },

   {
    "name": "Bell Pepper",
    "image": "assets/images/bellpepper.jpeg",
    "price": "N300.00",
    "farm":"Amazing Farms",
    "description":
        "Bell pepper is a member of the bell family. It is a source of many health benefits, including a reduced risk of heart disease and cancer. It is also a source of many other health benefits.",
    "category": "Vegetables",
    "quantity": "25",
    "unit": "Kg",
    "id": "6",
    "isFavourite": false,
    "isInCart": false,
    "totalPrice": "N1000.00",
    "totalQuantity": "1",
    "totalUnit": "Kg",
    "totalAmount": "₹10",
  },

   {
    "name": "Bell Pepper",
    "image": "assets/svgs/cucumber.jpg",
    "price": "N300.00",
    "farm":"Brook Farms",
    "description":
        "Bell pepper is a member of the bell family. It is a source of many health benefits, including a reduced risk of heart disease and cancer. It is also a source of many other health benefits.",
    "category": "Vegetables",
    "quantity": "25",
    "unit": "Kg",
    "id": "6",
    "isFavourite": false,
    "isInCart": false,
    "totalPrice": "N1000.00",
    "totalQuantity": "1",
    "totalUnit": "Kg",
    "totalAmount": "₹10",
  },

   {
    "name": "Avocado",
    "image": "assets/images/avocado.jpeg",
    "price": "N300.00",
    "farm":"Stein Farms",
    "description":
        "Avocado is a member of the avocado family. It is a source of many health benefits, including a reduced risk of heart disease and cancer. It is also a source of many other health benefits.",
    "category": "Vegetables",
    "quantity": "25",
    "unit": "Kg",
    "id": "6",
    "isFavourite": false,
    "isInCart": false,
    "totalPrice": "N1000.00",
    "totalQuantity": "1",
    "totalUnit": "Kg",
    "totalAmount": "₹10",
  },

 {
    "name": "Lemon",
    "image": "assets/images/lemon.jpeg",
    "price": "N300.00",
    "farm":"John Farms",
    "description":
        "Avocado is a member of the avocado family. It is a source of many health benefits, including a reduced risk of heart disease and cancer. It is also a source of many other health benefits.",
    "category": "Vegetables",
    "quantity": "25",
    "unit": "Kg",
    "id": "6",
    "isFavourite": false,
    "isInCart": false,
    "totalPrice": "N1000.00",
    "totalQuantity": "1",
    "totalUnit": "Kg",
    "totalAmount": "₹10",
  },
];
