// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBkv3L7AFbuCDO-yCHvh8j1Ml5hF2_GUXk',
    appId: '1:204514613386:android:7f237c2eed2682b08db573',
    messagingSenderId: '204514613386',
    projectId: 'farmx-60901',
    databaseURL: 'https://farmx-60901-default-rtdb.firebaseio.com',
    storageBucket: 'farmx-60901.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB7aM9Bi7Tl2p6co7ATFMfNhNDrCJRHpjs',
    appId: '1:204514613386:ios:2ed2b327e83551a88db573',
    messagingSenderId: '204514613386',
    projectId: 'farmx-60901',
    databaseURL: 'https://farmx-60901-default-rtdb.firebaseio.com',
    storageBucket: 'farmx-60901.appspot.com',
    iosClientId: '204514613386-as7ufrv4ggl5ntc725t2be9eunt3ogr2.apps.googleusercontent.com',
    iosBundleId: 'com.example.agrotechHackat',
  );
}
